//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1", ClrNamespace="Case3.FEWebwinkel.Schema.Messages")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bscatalogusbeheer:productupdate:v1", ClrNamespace="Case3.FEWebwinkel.Schema.ProductUpdate")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bscatalogusbeheer:product:v1", ClrNamespace="Case3.FEWebwinkel.Schema.Product")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bscatalogusbeheer:categorie:v1", ClrNamespace="Case3.FEWebwinkel.Schema.Categorie")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:common:fouten:v1", ClrNamespace="Case3.FEWebwinkel.Schema.Fouten")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bscatalogusbeheer:leverancier:v1", ClrNamespace="Case3.FEWebwinkel.Schema.Leverancier")]

namespace Case3.FEWebwinkel.Schema.Messages
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgUpdateCatalogusRequest", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgUpdateCatalogusRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.ProductUpdate.ProductUpdateCollection ProductUpdateListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Case3.FEWebwinkel.Schema.ProductUpdate.ProductUpdateCollection ProductUpdateList
        {
            get
            {
                return this.ProductUpdateListField;
            }
            set
            {
                this.ProductUpdateListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgUpdateCatalogusResult", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgUpdateCatalogusResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.ProductUpdate.ProductUpdateResultaatCollection ResultatenField;
        
        private bool SuccesField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Case3.FEWebwinkel.Schema.ProductUpdate.ProductUpdateResultaatCollection Resultaten
        {
            get
            {
                return this.ResultatenField;
            }
            set
            {
                this.ResultatenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindProductByIdRequest", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindProductByIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindProductByIdResult", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindProductByIdResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.Product.Product ProductField;
        
        private bool SuccesField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Case3.FEWebwinkel.Schema.Product.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindProductsRequest", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindProductsRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NaamFilterField;
        
        private string BeschrijvingFilterField;
        
        private System.Nullable<decimal> MinimumPrijsField;
        
        private System.Nullable<decimal> MaximumPrijsField;
        
        private System.Nullable<int> CategorieField;
        
        private System.Nullable<int> LeverancierField;
        
        private Case3.FEWebwinkel.Schema.Messages.Sorteerveld SorteerveldField;
        
        private Case3.FEWebwinkel.Schema.Messages.Sorteerrichting SorteerrichtingField;
        
        private bool AlleenLeverbareProductenField;
        
        private int PageField;
        
        private int PageSizeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaamFilter
        {
            get
            {
                return this.NaamFilterField;
            }
            set
            {
                this.NaamFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BeschrijvingFilter
        {
            get
            {
                return this.BeschrijvingFilterField;
            }
            set
            {
                this.BeschrijvingFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<decimal> MinimumPrijs
        {
            get
            {
                return this.MinimumPrijsField;
            }
            set
            {
                this.MinimumPrijsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> MaximumPrijs
        {
            get
            {
                return this.MaximumPrijsField;
            }
            set
            {
                this.MaximumPrijsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> Categorie
        {
            get
            {
                return this.CategorieField;
            }
            set
            {
                this.CategorieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> Leverancier
        {
            get
            {
                return this.LeverancierField;
            }
            set
            {
                this.LeverancierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public Case3.FEWebwinkel.Schema.Messages.Sorteerveld Sorteerveld
        {
            get
            {
                return this.SorteerveldField;
            }
            set
            {
                this.SorteerveldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public Case3.FEWebwinkel.Schema.Messages.Sorteerrichting Sorteerrichting
        {
            get
            {
                return this.SorteerrichtingField;
            }
            set
            {
                this.SorteerrichtingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool AlleenLeverbareProducten
        {
            get
            {
                return this.AlleenLeverbareProductenField;
            }
            set
            {
                this.AlleenLeverbareProductenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sorteerveld", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public enum Sorteerveld : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Naam = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prijs = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeverancierNaam = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sorteerrichting", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public enum Sorteerrichting : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Oplopend = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aflopend = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindProductsResult", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindProductsResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.Product.ProductCollection ProductsField;
        
        private int PageField;
        
        private int PageSizeField;
        
        private int PageCountField;
        
        private bool SuccesField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.FEWebwinkel.Schema.Product.ProductCollection Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int PageCount
        {
            get
            {
                return this.PageCountField;
            }
            set
            {
                this.PageCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindLeveranciersRequest", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindLeveranciersRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NaamFilterField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NaamFilter
        {
            get
            {
                return this.NaamFilterField;
            }
            set
            {
                this.NaamFilterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindLeveranciersResult", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindLeveranciersResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.Leverancier.LeverancierCollection LeveranciersField;
        
        private bool SuccesField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Case3.FEWebwinkel.Schema.Leverancier.LeverancierCollection Leveranciers
        {
            get
            {
                return this.LeveranciersField;
            }
            set
            {
                this.LeveranciersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindCategorieenRequest", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindCategorieenRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindCategorieenResult", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:messages:v1")]
    public partial class MsgFindCategorieenResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.Categorie.CategorieCollection CategorieenField;
        
        private bool SuccesField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Case3.FEWebwinkel.Schema.Categorie.CategorieCollection Categorieen
        {
            get
            {
                return this.CategorieenField;
            }
            set
            {
                this.CategorieenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
}
namespace Case3.FEWebwinkel.Schema.ProductUpdate
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductUpdateCollection", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:productupdate:v1", ItemName="ProductUpdate")]
    public class ProductUpdateCollection : System.Collections.Generic.List<Case3.FEWebwinkel.Schema.ProductUpdate.ProductUpdate>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUpdate", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:productupdate:v1")]
    public partial class ProductUpdate : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.ProductUpdate.UpdateActie UpdateActieField;
        
        private Case3.FEWebwinkel.Schema.Product.Product ProductField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Case3.FEWebwinkel.Schema.ProductUpdate.UpdateActie UpdateActie
        {
            get
            {
                return this.UpdateActieField;
            }
            set
            {
                this.UpdateActieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public Case3.FEWebwinkel.Schema.Product.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateActie", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:productupdate:v1")]
    public enum UpdateActie : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateOrInsert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductUpdateResultaatCollection", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:productupdate:v1", ItemName="ProductUpdateResultaat")]
    public class ProductUpdateResultaatCollection : System.Collections.Generic.List<Case3.FEWebwinkel.Schema.ProductUpdate.ProductUpdateResultaat>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUpdateResultaat", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:productupdate:v1")]
    public partial class ProductUpdateResultaat : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.FEWebwinkel.Schema.Product.ProductRef ProductRefField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutMeldingField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Case3.FEWebwinkel.Schema.Product.ProductRef ProductRef
        {
            get
            {
                return this.ProductRefField;
            }
            set
            {
                this.ProductRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutMelding FoutMelding
        {
            get
            {
                return this.FoutMeldingField;
            }
            set
            {
                this.FoutMeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
}
namespace Case3.FEWebwinkel.Schema.Product
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:product:v1")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IdField;
        
        private string AfbeeldingURLField;
        
        private string BeschrijvingField;
        
        private string LeverancierNaamField;
        
        private string LeveranciersProductIdField;
        
        private System.Nullable<System.DateTime> LeverbaarTotField;
        
        private System.Nullable<System.DateTime> LeverbaarVanafField;
        
        private string NaamField;
        
        private System.Nullable<decimal> PrijsField;
        
        private Case3.FEWebwinkel.Schema.Categorie.CategorieCollection CategorieLijstField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string AfbeeldingURL
        {
            get
            {
                return this.AfbeeldingURLField;
            }
            set
            {
                this.AfbeeldingURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Beschrijving
        {
            get
            {
                return this.BeschrijvingField;
            }
            set
            {
                this.BeschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string LeverancierNaam
        {
            get
            {
                return this.LeverancierNaamField;
            }
            set
            {
                this.LeverancierNaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string LeveranciersProductId
        {
            get
            {
                return this.LeveranciersProductIdField;
            }
            set
            {
                this.LeveranciersProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> LeverbaarTot
        {
            get
            {
                return this.LeverbaarTotField;
            }
            set
            {
                this.LeverbaarTotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> LeverbaarVanaf
        {
            get
            {
                return this.LeverbaarVanafField;
            }
            set
            {
                this.LeverbaarVanafField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Naam
        {
            get
            {
                return this.NaamField;
            }
            set
            {
                this.NaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<decimal> Prijs
        {
            get
            {
                return this.PrijsField;
            }
            set
            {
                this.PrijsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Case3.FEWebwinkel.Schema.Categorie.CategorieCollection CategorieLijst
        {
            get
            {
                return this.CategorieLijstField;
            }
            set
            {
                this.CategorieLijstField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRef", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:product:v1")]
    public partial class ProductRef : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string LeveranciersProductIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeveranciersProductId
        {
            get
            {
                return this.LeveranciersProductIdField;
            }
            set
            {
                this.LeveranciersProductIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductCollection", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:product:v1", ItemName="Product")]
    public class ProductCollection : System.Collections.Generic.List<Case3.FEWebwinkel.Schema.Product.Product>
    {
    }
}
namespace Case3.FEWebwinkel.Schema.Categorie
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CategorieCollection", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:categorie:v1", ItemName="Categorie")]
    public class CategorieCollection : System.Collections.Generic.List<Case3.FEWebwinkel.Schema.Categorie.Categorie>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categorie", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:categorie:v1")]
    public partial class Categorie : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IdField;
        
        private string NaamField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Naam
        {
            get
            {
                return this.NaamField;
            }
            set
            {
                this.NaamField = value;
            }
        }
    }
}
namespace Case3.FEWebwinkel.Schema.Fouten
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoutMelding", Namespace="urn:schemas-www-kantilever-nl:common:fouten:v1")]
    public partial class FoutMelding : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BronField;
        
        private int NummerField;
        
        private string MeldingField;
        
        private Case3.FEWebwinkel.Schema.Fouten.FoutErnst NiveauField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Bron
        {
            get
            {
                return this.BronField;
            }
            set
            {
                this.BronField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nummer
        {
            get
            {
                return this.NummerField;
            }
            set
            {
                this.NummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Melding
        {
            get
            {
                return this.MeldingField;
            }
            set
            {
                this.MeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Case3.FEWebwinkel.Schema.Fouten.FoutErnst Niveau
        {
            get
            {
                return this.NiveauField;
            }
            set
            {
                this.NiveauField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoutErnst", Namespace="urn:schemas-www-kantilever-nl:common:fouten:v1")]
    public enum FoutErnst : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kritisch = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waarschuwing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Melding = 2,
    }
}
namespace Case3.FEWebwinkel.Schema.Leverancier
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LeverancierCollection", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:leverancier:v1", ItemName="Leverancier")]
    public class LeverancierCollection : System.Collections.Generic.List<Case3.FEWebwinkel.Schema.Leverancier.Leverancier>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leverancier", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:leverancier:v1")]
    public partial class Leverancier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IdField;
        
        private string NaamField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam
        {
            get
            {
                return this.NaamField;
            }
            set
            {
                this.NaamField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:kantilever:bscatalogusbeheer:v1", ConfigurationName="ICatalogusBeheer")]
public interface ICatalogusBeheer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/UpdateCatalogus", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/UpdateCatalogusResponse")]
    Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusResult UpdateCatalogus(Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/UpdateCatalogus", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/UpdateCatalogusResponse")]
    System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusResult> UpdateCatalogusAsync(Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProductById", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProductByIdResponse")]
    Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdResult FindProductById(Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProductById", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProductByIdResponse")]
    System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdResult> FindProductByIdAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProducts", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProductsResponse")]
    Case3.FEWebwinkel.Schema.Messages.MsgFindProductsResult FindProducts(Case3.FEWebwinkel.Schema.Messages.MsgFindProductsRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProducts", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindProductsResponse")]
    System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindProductsResult> FindProductsAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindProductsRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindLeveranciers", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindLeveranciersResponse")]
    Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersResult FindLeveranciers(Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindLeveranciers", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindLeveranciersResponse")]
    System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersResult> FindLeveranciersAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindCategorieen", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindCategorieenResponse")]
    Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenResult FindCategorieen(Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindCategorieen", ReplyAction="urn:kantilever:bscatalogusbeheer:v1/ICatalogusBeheer/FindCategorieenResponse")]
    System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenResult> FindCategorieenAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenRequest message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICatalogusBeheerChannel : ICatalogusBeheer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CatalogusBeheerClient : System.ServiceModel.ClientBase<ICatalogusBeheer>, ICatalogusBeheer
{
    
    public CatalogusBeheerClient()
    {
    }
    
    public CatalogusBeheerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CatalogusBeheerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CatalogusBeheerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CatalogusBeheerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusResult UpdateCatalogus(Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusRequest message)
    {
        return base.Channel.UpdateCatalogus(message);
    }
    
    public System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusResult> UpdateCatalogusAsync(Case3.FEWebwinkel.Schema.Messages.MsgUpdateCatalogusRequest message)
    {
        return base.Channel.UpdateCatalogusAsync(message);
    }
    
    public Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdResult FindProductById(Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdRequest message)
    {
        return base.Channel.FindProductById(message);
    }
    
    public System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdResult> FindProductByIdAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindProductByIdRequest message)
    {
        return base.Channel.FindProductByIdAsync(message);
    }
    
    public Case3.FEWebwinkel.Schema.Messages.MsgFindProductsResult FindProducts(Case3.FEWebwinkel.Schema.Messages.MsgFindProductsRequest message)
    {
        return base.Channel.FindProducts(message);
    }
    
    public System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindProductsResult> FindProductsAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindProductsRequest message)
    {
        return base.Channel.FindProductsAsync(message);
    }
    
    public Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersResult FindLeveranciers(Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersRequest message)
    {
        return base.Channel.FindLeveranciers(message);
    }
    
    public System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersResult> FindLeveranciersAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindLeveranciersRequest message)
    {
        return base.Channel.FindLeveranciersAsync(message);
    }
    
    public Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenResult FindCategorieen(Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenRequest message)
    {
        return base.Channel.FindCategorieen(message);
    }
    
    public System.Threading.Tasks.Task<Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenResult> FindCategorieenAsync(Case3.FEWebwinkel.Schema.Messages.MsgFindCategorieenRequest message)
    {
        return base.Channel.FindCategorieenAsync(message);
    }
}
