//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1", ClrNamespace="schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraadupdate:v1", ClrNamespace="schemaswwwkantilevernl.bsvoorraadbeheer.voorraadupdate.v1")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraad:v1", ClrNamespace="schemaswwwkantilevernl.bsvoorraadbeheer.voorraad.v1")]

namespace schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgUpdateVoorraadRequest", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgUpdateVoorraadRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.ProductNS.ProductRef ProductField;
        
        private schemaswwwkantilevernl.bsvoorraadbeheer.voorraadupdate.v1.UpdateProductVoorraad UpdateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.ProductNS.ProductRef Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public schemaswwwkantilevernl.bsvoorraadbeheer.voorraadupdate.v1.UpdateProductVoorraad Update
        {
            get
            {
                return this.UpdateField;
            }
            set
            {
                this.UpdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgUpdateVoorraadResult", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgUpdateVoorraadResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemaswwwkantilevernl.bsvoorraadbeheer.voorraad.v1.ProductVoorraad ProductVoorraadField;
        
        private bool SuccesField;
        
        private Case3.PcSWinkelen.Schema.FoutenNS.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public schemaswwwkantilevernl.bsvoorraadbeheer.voorraad.v1.ProductVoorraad ProductVoorraad
        {
            get
            {
                return this.ProductVoorraadField;
            }
            set
            {
                this.ProductVoorraadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.PcSWinkelen.Schema.FoutenNS.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindVoorraadRequest", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgFindVoorraadRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.ProductNS.ProductRef ProductField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.ProductNS.ProductRef Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindVoorraadResult", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgFindVoorraadResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemaswwwkantilevernl.bsvoorraadbeheer.voorraad.v1.ProductVoorraad ProductVoorraadField;
        
        private bool SuccesField;
        
        private Case3.PcSWinkelen.Schema.FoutenNS.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public schemaswwwkantilevernl.bsvoorraadbeheer.voorraad.v1.ProductVoorraad ProductVoorraad
        {
            get
            {
                return this.ProductVoorraadField;
            }
            set
            {
                this.ProductVoorraadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.PcSWinkelen.Schema.FoutenNS.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
}
namespace schemaswwwkantilevernl.bsvoorraadbeheer.voorraadupdate.v1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProductVoorraad", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraadupdate:v1")]
    public partial class UpdateProductVoorraad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemaswwwkantilevernl.bsvoorraadbeheer.voorraadupdate.v1.UpdateActie ActieField;
        
        private int AantalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public schemaswwwkantilevernl.bsvoorraadbeheer.voorraadupdate.v1.UpdateActie Actie
        {
            get
            {
                return this.ActieField;
            }
            set
            {
                this.ActieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Aantal
        {
            get
            {
                return this.AantalField;
            }
            set
            {
                this.AantalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateActie", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraadupdate:v1")]
    public enum UpdateActie : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 1,
    }
}
namespace schemaswwwkantilevernl.bsvoorraadbeheer.voorraad.v1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductVoorraad", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraad:v1")]
    public partial class ProductVoorraad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.ProductNS.ProductRef ProductField;
        
        private int VoorraadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.ProductNS.ProductRef Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Voorraad
        {
            get
            {
                return this.VoorraadField;
            }
            set
            {
                this.VoorraadField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:kantilever:bsvoorraadbeheer:v1", ConfigurationName="IVoorraadBeheer")]
public interface IVoorraadBeheer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraadResponse")]
    schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadResult UpdateVoorraad(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraadResponse")]
    System.Threading.Tasks.Task<schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadResult> UpdateVoorraadAsync(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraadResponse")]
    schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadResult FindVoorraad(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraadResponse")]
    System.Threading.Tasks.Task<schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadResult> FindVoorraadAsync(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadRequest message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVoorraadBeheerChannel : IVoorraadBeheer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VoorraadBeheerClient : System.ServiceModel.ClientBase<IVoorraadBeheer>, IVoorraadBeheer
{
    
    public VoorraadBeheerClient()
    {
    }
    
    public VoorraadBeheerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VoorraadBeheerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VoorraadBeheerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VoorraadBeheerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadResult UpdateVoorraad(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadRequest message)
    {
        return base.Channel.UpdateVoorraad(message);
    }
    
    public System.Threading.Tasks.Task<schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadResult> UpdateVoorraadAsync(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgUpdateVoorraadRequest message)
    {
        return base.Channel.UpdateVoorraadAsync(message);
    }
    
    public schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadResult FindVoorraad(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadRequest message)
    {
        return base.Channel.FindVoorraad(message);
    }
    
    public System.Threading.Tasks.Task<schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadResult> FindVoorraadAsync(schemaswwwkantilevernl.bsvoorraadbeheer.messages.v1.MsgFindVoorraadRequest message)
    {
        return base.Channel.FindVoorraadAsync(message);
    }
}
