//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1", ClrNamespace="Case3.PcSWinkelen.Schema.Messages")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bscatalogusbeheer:product:v1", ClrNamespace="Case3.PcSWinkelen.Schema.Product")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraadupdate:v1", ClrNamespace="Case3.PcSWinkelen.Schema.VoorraadUpdate")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraad:v1", ClrNamespace="Case3.PcSWinkelen.Schema.Voorraad")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:schemas-www-kantilever-nl:common:fouten:v1", ClrNamespace="Case3.PcSWinkelen.Schema.Fouten")]

namespace Case3.PcSWinkelen.Schema.Messages
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgUpdateVoorraadRequest", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgUpdateVoorraadRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.Product.ProductRef ProductField;
        
        private Case3.PcSWinkelen.Schema.VoorraadUpdate.UpdateProductVoorraad UpdateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.Product.ProductRef Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.VoorraadUpdate.UpdateProductVoorraad Update
        {
            get
            {
                return this.UpdateField;
            }
            set
            {
                this.UpdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgUpdateVoorraadResult", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgUpdateVoorraadResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.Voorraad.ProductVoorraad ProductVoorraadField;
        
        private bool SuccesField;
        
        private Case3.PcSWinkelen.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.Voorraad.ProductVoorraad ProductVoorraad
        {
            get
            {
                return this.ProductVoorraadField;
            }
            set
            {
                this.ProductVoorraadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.PcSWinkelen.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindVoorraadRequest", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgFindVoorraadRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.Product.ProductRef ProductField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.Product.ProductRef Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgFindVoorraadResult", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:messages:v1")]
    public partial class MsgFindVoorraadResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.Voorraad.ProductVoorraad ProductVoorraadField;
        
        private bool SuccesField;
        
        private Case3.PcSWinkelen.Schema.Fouten.FoutMelding FoutmeldingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.Voorraad.ProductVoorraad ProductVoorraad
        {
            get
            {
                return this.ProductVoorraadField;
            }
            set
            {
                this.ProductVoorraadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Case3.PcSWinkelen.Schema.Fouten.FoutMelding Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
    }
}
namespace Case3.PcSWinkelen.Schema.Product
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRef", Namespace="urn:schemas-www-kantilever-nl:bscatalogusbeheer:product:v1")]
    public partial class ProductRef : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string LeveranciersProductIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeveranciersProductId
        {
            get
            {
                return this.LeveranciersProductIdField;
            }
            set
            {
                this.LeveranciersProductIdField = value;
            }
        }
    }
}
namespace Case3.PcSWinkelen.Schema.VoorraadUpdate
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProductVoorraad", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraadupdate:v1")]
    public partial class UpdateProductVoorraad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.VoorraadUpdate.UpdateActie ActieField;
        
        private int AantalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Case3.PcSWinkelen.Schema.VoorraadUpdate.UpdateActie Actie
        {
            get
            {
                return this.ActieField;
            }
            set
            {
                this.ActieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Aantal
        {
            get
            {
                return this.AantalField;
            }
            set
            {
                this.AantalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateActie", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraadupdate:v1")]
    public enum UpdateActie : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 1,
    }
}
namespace Case3.PcSWinkelen.Schema.Voorraad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductVoorraad", Namespace="urn:schemas-www-kantilever-nl:bsvoorraadbeheer:voorraad:v1")]
    public partial class ProductVoorraad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Case3.PcSWinkelen.Schema.Product.ProductRef ProductField;
        
        private int VoorraadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Case3.PcSWinkelen.Schema.Product.ProductRef Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Voorraad
        {
            get
            {
                return this.VoorraadField;
            }
            set
            {
                this.VoorraadField = value;
            }
        }
    }
}
namespace Case3.PcSWinkelen.Schema.Fouten
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoutMelding", Namespace="urn:schemas-www-kantilever-nl:common:fouten:v1")]
    public partial class FoutMelding : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BronField;
        
        private int NummerField;
        
        private string MeldingField;
        
        private Case3.PcSWinkelen.Schema.Fouten.FoutErnst NiveauField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Bron
        {
            get
            {
                return this.BronField;
            }
            set
            {
                this.BronField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nummer
        {
            get
            {
                return this.NummerField;
            }
            set
            {
                this.NummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Melding
        {
            get
            {
                return this.MeldingField;
            }
            set
            {
                this.MeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Case3.PcSWinkelen.Schema.Fouten.FoutErnst Niveau
        {
            get
            {
                return this.NiveauField;
            }
            set
            {
                this.NiveauField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoutErnst", Namespace="urn:schemas-www-kantilever-nl:common:fouten:v1")]
    public enum FoutErnst : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kritisch = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waarschuwing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Melding = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:kantilever:bsvoorraadbeheer:v1", ConfigurationName="IVoorraadBeheer")]
public interface IVoorraadBeheer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraadResponse")]
    Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadResult UpdateVoorraad(Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/UpdateVoorraadResponse")]
    System.Threading.Tasks.Task<Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadResult> UpdateVoorraadAsync(Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraadResponse")]
    Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadResult FindVoorraad(Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadRequest message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraad", ReplyAction="urn:kantilever:bsvoorraadbeheer:v1/IVoorraadBeheer/FindVoorraadResponse")]
    System.Threading.Tasks.Task<Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadResult> FindVoorraadAsync(Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadRequest message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVoorraadBeheerChannel : IVoorraadBeheer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VoorraadBeheerClient : System.ServiceModel.ClientBase<IVoorraadBeheer>, IVoorraadBeheer
{
    
    public VoorraadBeheerClient()
    {
    }
    
    public VoorraadBeheerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VoorraadBeheerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VoorraadBeheerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VoorraadBeheerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadResult UpdateVoorraad(Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadRequest message)
    {
        return base.Channel.UpdateVoorraad(message);
    }
    
    public System.Threading.Tasks.Task<Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadResult> UpdateVoorraadAsync(Case3.PcSWinkelen.Schema.Messages.MsgUpdateVoorraadRequest message)
    {
        return base.Channel.UpdateVoorraadAsync(message);
    }
    
    public Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadResult FindVoorraad(Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadRequest message)
    {
        return base.Channel.FindVoorraad(message);
    }
    
    public System.Threading.Tasks.Task<Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadResult> FindVoorraadAsync(Case3.PcSWinkelen.Schema.Messages.MsgFindVoorraadRequest message)
    {
        return base.Channel.FindVoorraadAsync(message);
    }
}
